#!/bin/sh
set -e

OPTIONS_SPEC="\
$(basename $0)

updates runtime from upstream vim ftp
--
"
SUBDIRECTORY_OK=
. "$(git --exec-path)/git-sh-setup"
require_work_tree
cd_to_toplevel

git rev-parse --verify HEAD > /dev/null && \
    git update-index --refresh && \
    git diff-files --quiet && \
    git diff-index --cached --quiet HEAD -- \
    || die "Your tree is unclean, can't do that..."

which rsync >/dev/null 2>&1 || die "You need rsync installed for this script..."

checkout_and_merge() {
    git checkout $1
    if ! git merge $2; then
        echo "Merge conflict -- fix the problem and then exit the subshell to continue"
        if ! $SHELL; then
            echo "Non-zero exit status from merge conflict.  Exiting update script."
            exit
        fi
    fi
}

git checkout upstream-runtime --

rsync -avzcP --delete --exclude="README.txt" --exclude="getdos.aap" \
      --exclude="getunix.aap" --exclude="main.aap" --exclude="dos" \
      --exclude="spell" \
      ftp.vim.org::Vim/runtime/ runtime

rsync -avzcP --delete --include="en.*" --include="he.vim" --include="yi.vim" \
      --include="cleanadd.vim" --exclude="*" \
      ftp.vim.org::Vim/runtime/spell/ runtime/spell

git add -A runtime
git commit -m 'Sync runtime files'

for b in deb/runtime debian; do
    checkout_and_merge $b upstream-runtime
done
